<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>CalComClone</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
      <Folder Include="Responses\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CalComClone.Core\CalComClone.Core.csproj" />
      <ProjectReference Include="..\CalComClone.UseCases\CalComClone.UseCases.csproj" />
      <ProjectReference Include="..\CalComClone.Infrastructure\CalComClone.Infrastructure.csproj" />
    </ItemGroup>

</Project>
